### ISSUE TITLE
0.3.0.8: src/Diagrams/Haddock.hs:458:55: Couldn't match expected type

### ISSUE THREAD

**Issue by juhp** [diagrams/diagrams-haddock#26]
diagrams-haddock-0.3.0.8 failed to build in Stackage Nightly:

```
src/Diagrams/Haddock.hs:458:55:
    Couldn't match expected type ‘[t0]
                                  -> Bool -> Options SVG V2 Double’
                with actual type ‘Options SVG V2 Double’
    The function ‘SVGOptions’ is applied to five arguments,
    but its type ‘Diagrams.Size.SizeSpec V2 Double
                  -> Maybe diagrams-svg-1.3.1.7:Graphics.Rendering.SVG.SvgM
                  -> Data.Text.Internal.Text
                  -> Options SVG V2 Double’
    has only three
    In the third argument of ‘DB.mkBuildOpts’, namely
      ‘(SVGOptions (mkSizeSpec2D w h) Nothing "" [] False)’
    In the first argument of ‘(&)’, namely
      ‘DB.mkBuildOpts
         SVG zero (SVGOptions (mkSizeSpec2D w h) Nothing "" [] False)’
```

**Comment by byorgey** [comment]
Sorry, I wrote that too fast.  Let me be more precise. It looks like what happened is:

- The `diagrams-haddock` master branch included some changes to track (breaking) changes on `diagrams-svg` master, namely: diagrams/diagrams-haddock@2e654ce .
- `lucid-svg-0.6` was released, and https://github.com/fpco/stackage/issues/976 was filed since `diagrams-haddock` depends on `lucid-svg`.
- The 0.3.0.8 release of `diagrams-haddock` was cut from the `master` branch, accidentally including the aforementioned changes in addition to the `lucid-svg` version bump.
- This caused the `diagrams-haddock` build to fail, as reported here.
- At some point a new release of `diagrams-svg-1.3.1.8` was also cut from the `master` branch of `diagrams-svg`.  This means that building `diagrams-haddock` from Hackage now succeeds, BUT both `diagrams-svg` and `diagrams-haddock` have introduced breaking changes without a major version bump.

**Comment by byorgey** [comment]
Another confounding issue: it seems that the latest changes on `diagrams-svg` master REQUIRE `lucid-svg-0.6`.

**Comment by jeffreyrosenbluth** [comment]
This is my fault, I tried to squeeze in the update to lucid-svg 0.6 to fix
a bug, but was too hasty.
Let me know what you think should be done from hear and I'll take care of
it.
Sorry about that

**Comment by bergey** [comment]
I obviously released without enough testing also.  I should have time to look at this tomorrow morning.

**Comment by byorgey** [comment]
Will the previous release of `diagrams-svg` (before the options updates)
compile with `lucid-svg-0.6`?

By the way, for the moment I deprecated `diagrams-svg-1.3.1.8`, since it
would cause any builds with stack to fail.  That puts us back in the
situation where `diagrams-haddock` fails with a type error; at least that
is not installed by default with diagrams so it has less of an immediate
impact.

**Comment by jeffreyrosenbluth** [comment]
Yes, I believe so, the change to lucid-svg was restricted to the `textPath` function
which we don't use in diagrams.

**Comment by byorgey** [comment]
OK, in that case I think the thing to do is to simply bump the upper bound on `lucid-svg` in `diagrams-svg` (supporting both 0.5 and 0.6 if we can), and release `diagrams-svg-1.3.1.9` from the `release` branch, and then make a corresponding release of `diagrams-haddock-0.3.0.9` also from the `release` branch (which I just created).  Unless there is something that I am missing.

**Comment by byorgey** [comment]
We should probably also mark `diagrams-haddock-0.3.0.8` as deprecated on Hackage.

**Comment by jeffreyrosenbluth** [comment]
Sounds good, I'll try to get to this today.

**Comment by byorgey** [comment]
Thanks @jeffreyrosenbluth .  @juhp, it looks like everything is building again (http://gondor.cs.hendrix.edu:8080/job/Diagrams%20HEAD/21/ ).  Let us know if you see any other build failures from stackage.
